name: tests-frontend

on:
  push:
    paths:
      - "frontend/**"
      - ".github/workflows/tests-frontend.yml"
  pull_request:
    paths:
      - "frontend/**"
      - ".github/workflows/tests-frontend.yml"
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version: "24.11.1"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Set up Chrome
        id: setup-chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install dependencies
        working-directory: frontend
        run: npm ci

      - name: Run tests
        working-directory: frontend
        env:
          CHROME_BIN: ${{ steps.setup-chrome.outputs.chrome-path }}
        run: npm test -- --watch=false --browsers=ChromeHeadlessNoSandbox
