{{- if .Values.sealedSecrets.backendCredentials.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ default (include "pantry.backendCredentialsSecretName" .) .Values.sealedSecrets.backendCredentials.name }}
  labels:
    {{- include "pantry.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  encryptedData:
    {{- toYaml .Values.sealedSecrets.backendCredentials.encryptedData | nindent 4 }}
  template:
    metadata:
      name: {{ default (include "pantry.backendCredentialsSecretName" .) .Values.sealedSecrets.backendCredentials.name }}
      labels:
        {{- include "pantry.labels" . | nindent 8 }}
        app.kubernetes.io/component: backend
    type: Opaque
{{- end }}

